import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Menu } from "@/components/layout/Menu/menu.component";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <nav className="my-10 mx-8 flex flex-wrap content-center">
          <div className="z-30">
            <h1 className="text-xl font-extrabold tracking-wide">
              Arthur
              <span className="font-normal ml-2">Fernandez</span>
            </h1>
          </div>
          <Menu />
        </nav>
        {children}
      </body>
    </html>
  );
}
